# ---------------------------------------------------------------------
# HIV_RT 
# ---------------------------------------------------------------------
#Alignment: HIV_RT.fasta
#Newick: HIV_RT.fasta.treefile
#Tag: HIV_RT

# HIV_RT Simulations --------------------------------------------------
#Alignment: HIV-RT_simulations_o1_s300_r1.replicate.1.fasta
#Newick: HIV-RT_simulations_o1_s300_r1.replicate.1.newick
#Tag: HIV_RT_simulations_o1

#Alignment: HIV-RT_simulations_o01_s300_r1.replicate.1.fasta
#Newick: HIV-RT_simulations_o01_s300_r1.replicate.1.newick
#Tag: HIV_RT_simulations_o01

#Alignment: HIV-RT_simulations_o10_s300_r1.replicate.1.fasta
#Newick: HIV-RT_simulations_o10_s300_r1.replicate.1.newick
#Tag: HIV_RT_simulations_o10

# ---------------------------------------------------------------------
# TP53 
# ---------------------------------------------------------------------
#Alignment: TP53_refseq_cds_CodonAligned.fas
#Newick: TP53_refseq_cds_CodonAligned.nwk
#Tag: TP53

# TP53 Simulations ----------------------------------------------------
#Alignment: TP53_simulations_o01_s500_r1.replicate.1.fasta
#Newick: TP53_simulations_o01_s500_r1.replicate.1.newick

#Alignment: TP53_simulations_o1_s500_r1.replicate.1.fasta
#Newick: TP53_simulations_o1_s500_r1.replicate.1.newick

#Alignment: TP53_simulations_o10_s500_r1.replicate.1.fasta
#Newick: TP53_simulations_o10_s500_r1.replicate.1.newick
#Tag: TP53_simulations_o10

# ---------------------------------------------------------------------
# IAV
# ---------------------------------------------------------------------
#Alignment: IAV_Chen.fasta
#Newick: IAV_Chen.fasta.treefile
#Tag: IAV_Chen

# IAV Chen Simulations ------------------------------------------------
#Alignment: IAV_Chen_simulations_o01_s300_r1.replicate.1.fasta
#Newick: IAV_Chen_simulations_o01_s300_r1.replicate.1.newick
#Tag: IAV_Chen_simulations_o01

#Alignment: IAV_Chen_simulations_o1_s300_r1.replicate.1.fasta
#Newick: IAV_Chen_simulations_o1_s300_r1.replicate.1.newick
#Tag: IAV_Chen_simulations_o1

#Alignment: IAV_Chen_simulations_o10_s300_r1.replicate.1.fasta
#Newick: IAV_Chen_simulations_o10_s300_r1.replicate.1.newick
#Tag: IAV_Chen_simulations_o10


# ---------------------------------------------------------------------
# bglobin
# ---------------------------------------------------------------------
Alignment: bglobin.nex.fasta
Newick: bglobin.nex.newick
Tag: bglobin



# ---------------------------------------------------------------------
# User specified
# ---------------------------------------------------------------------

OutputDirectory: Results
WD: /home/tuk13147/work/MESSI

# End of file
