# -*- coding: utf-8 -*-
"""
Subsampling_with_TN93.py
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13sFTPkBMccdD_Qpp8DuWhU4UN2ckVT5d
"""
# **Import libraries**"""
import random
import csv
from Bio import SeqIO
import os
from ete3 import Tree

# Declares

"""# **Helper functions**"""

def sort(distances):
  with open(distances, "r") as f:
    csv_input = csv.DictReader(f)
    data = sorted(csv_input, key=lambda row: (row['Distance']))
  return data

def output_dna(fasta, excluded_IDs):
  global num_seqs
  x = num_seqs - len(excluded_IDs)

  print("# Output DNA exclusion list length", len(excluded_IDs))
  #output_file = fasta + "_subsampled_" + str(len(excluded_IDs)) + ".fasta"
  #output_file = fasta + "." + str(len(excluded_IDs)) + ".subsampled"
  output_file = fasta + "." + str(x) + ".subsampled.fasta"
  
  # Create empty output file
  with open(os.path.join(output_dir, output_file.split("/")[-1]), 'w') as fp:
    fp.write('')
  #end with
  
  with open(fasta, "r") as handle:
    for n, record in enumerate(SeqIO.parse(handle, "fasta")):
      id = record.id 
      if id in excluded_IDs: 
        continue
      #end if    
      desc = record.description
      seq = record.seq
      #output fasta
      with open(os.path.join(output_dir, output_file.split("/")[-1]), 'a') as f_out:
        SeqIO.write(record, f_out, "fasta")
      #end with
  #end with
  
  print("# Saved to (subsampled fasta file):", os.path.join(output_dir, output_file.split("/")[-1]))
#end method

def output_nwk(tree, excluded_IDs, all_record_IDs):
  global num_seqs
  x = num_seqs - len(excluded_IDs)
  print("# Output TREE exclusion list length", len(excluded_IDs))
  
  output_file = tree + "." + str(len(excluded_IDs)) + ".subsampled.nwk"
  
  output_file_print = tree + "." + str(x) + ".subsampled.nwk" # for some reason this is messing up.
  # printing to (says it is saving to one file), and saving in another.
    
  # Create empty output file
  #with open(os.path.join(output_dir, output_file.split("/")[-1]), 'w') as fp:
  #  fp.write('')
  #end with
  
  # Newick, branch pruning logic.
  try:
      t = Tree(tree)
  except:
      t = Tree(tree, format=1)
  #end try

  # Pruning logic here --------------------------------------------
  KeepThese = []
  #for item in excluded_IDs:
  for item in all_record_IDs:
      if item not in excluded_IDs:
          KeepThese.append(item)
      #end if
  #end for
   
  t.prune(tuple(KeepThese))
  #t.prune(tuple(excluded_IDs))
  #t.delete(tuple(excluded_IDs))
  
  #for item in excluded_IDs:
  #    G = t.search_nodes(name=item)[0]
  #    G.delete()
  
  outfile_tree_print = os.path.join(output_dir, output_file_print.split("/")[-1])
  #print("# outfile_tree (variable):", outfile_tree_print)
  
  #outfile_tree = os.path.join(output_dir, output_file.split("/")[-1])
  t.write(format=1, outfile=outfile_tree_print)
  
  print("# Saved to (newick file):", outfile_tree_print)
#end method

def get_num_seqs(fasta):
  count = 0
  with open(fasta, "r") as handle:
    for n, record in enumerate(SeqIO.parse(handle, "fasta")):
        #id = record.id 
        #desc = record.description
        #pseq = record.seq
        count += 1
    #end for
  return count
#end method

def get_record_ids(fasta):
  IDs = []
  with open(fasta, "r") as handle:
    for n, record in enumerate(SeqIO.parse(handle, "fasta")):
        #id = record.id
        #desc = record.description
        #pseq = record.seq
        #count += 1
        IDs.append(record.description)
    #end for
  return IDs
#end method

"""# **Subsampling logic**"""
def subsample(fasta, distances, num_seqs):
  global all_record_IDs
  print("# Sorting TN93 distances (low to high)")
  
  # This needs to be done once, no?
  sorted_distances = sort(distances) # returns a list of sorted (low to high) tn93 distances
  print ("# Sorting complete.")
  print()
  
  excluded_IDs = []
  print("# Entering subsampling logic and iterations")
  count = 1 # keep track of how many we have removed
  
  for n, entry in enumerate(sorted_distances):
    
    #if not count < int((num_seqs) * 0.75): # Stop at 25% of of the original number of sequences
    #  break
    #end if
    
    #if not count < 3:
    #  break
    #end if
    
    ID1, ID2, D = entry["ID1"], entry["ID2"], entry["Distance"]
    
    if ID1 in excluded_IDs and ID2 in excluded_IDs: # both have been previously excluded
      continue
    #end if
    
    # --- Make a choice
    to_exclude = ""
    if ID1 in excluded_IDs:
      if ID2 not in excluded_IDs:
        to_exclude = ID2
      #end if
    elif ID2 in excluded_IDs:
      if ID1 not in excluded_IDs:
        to_exclude = ID1
      #end if
    #end if
    
    # If neither IDs is in the exlusion list _ 
    # Randomly pick one of them
    if to_exclude == "":
      to_exclude = random.choice([ID1, ID2])
    #end if
    
    excluded_IDs.append(to_exclude)
    
    #print("# Chosen to exclude:", [to_exclude], D, ",".join([ID1, ID2]))
    print("# Iteration:", count)
    
    # Logic to exit at the end.
    if count == len(all_record_IDs):
        print("# Exiting last iteration, nothing left.")
        break
    #end if
    print("# Chosen to exclude:", [to_exclude])
    print("# Full entry of TN93 file(for debugging):", ",".join([ID1, ID2, D]))
    count += 1
    
    # Save the fasta, and the newick
    output_dna(fasta, excluded_IDs)
    output_nwk(tree, excluded_IDs, all_record_IDs)
    
    print()
  #end for
#end method

"""# **Main/Driver code**"""
fasta = snakemake.params.fasta
tree = snakemake.params.tree
distances = snakemake.params.distances
output_dir = snakemake.params.output_dir

print("## Working on (fasta) file --", fasta)

print("## Working on (TN93 Distances) file --", distances)

print("## Working on (Phylogenetic tree) file --", tree)

num_seqs = get_num_seqs(fasta)

print("## Number of sequences (in fasta):", num_seqs)

all_record_IDs = get_record_ids(fasta)
#print("## Number of records:", len(all_record_IDs))
#print(all_record_IDs)

print("## Starting subsampling...")
print()

# Heavy lifting done here .. function
subsample(fasta, distances, num_seqs)

# End of file

